### ISSUE TITLE
Out of memory errors

### ISSUE THREAD

**Issue by davidyell** [adamculp/php-code-quality#4]
Full disclosure: This is my first time trying Docker, after seeing your excellent talk at PHPUK19.

I have run two commands and both have written an out of memory exception to the resulting file.

`$ docker run -it --rm -v "$PWD":/app -w /app adamculp/php-code-quality:latest php /usr/local/lib/php-code-quality/vendor/bin/phploc -v --names "*.php" --exclude "vendor" . > ./phploc.txt`

Results in a file containing
```text
phploc 4.0.1 by Sebastian Bergmann.

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/lib/php-code-quality/vendor/phploc/phploc/src/Analyser.php on line 92

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/lib/php-code-quality/vendor/phploc/phploc/src/Analyser.php on line 209

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/lib/php-code-quality/vendor/phploc/phploc/src/Analyser.php on line 241

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/lib/php-code-quality/vendor/phploc/phploc/src/Analyser.php on line 124
```

When running the `phpcpd` command the file results in
```text
phpcpd 2.0.4 by Sebastian Bergmann.

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /usr/local/lib/php-code-quality/vendor/sebastian/phpcpd/src/Detector/Strategy/Default.php on line 45
```

Is this related to my locally installed PHP ini settings? Any guidance would be super. Thanks!

**Comment by hackzilla** [comment]
It seems to be a php memory limit as you thought.
You can override the limit by passing in `-d memory_limit=1G` to php.

e.g.
docker run -it --rm -v "$PWD":/app -w /app adamculp/php-code-quality:latest php **-d memory_limit=1G** /usr/local/lib/php-code-quality/vendor/bin/phploc -v --names "*.php" --exclude "vendor" .
phploc 4.0.1 by Sebastian Bergmann.


Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/lib/php-code-quality/vendor/phploc/phploc/src/Analyser.php on line 92

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/lib/php-code-quality/vendor/phploc/phploc/src/Analyser.php on line 209

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /usr/local/lib/php-code-quality/vendor/phploc/phploc/src/Analyser.php on line 241
Directories                                         37

**Comment by hackzilla** [comment]
Looking at the Dockerfile, it was set at 512M.

**Comment by davidyell** [comment]
Thanks @hackzilla that's worked for me. I wonder if the commands in the readme should be updated to reflect this.

**Comment by adamculp** [comment]
Great idea. Also, I'll be updating to use PHP 7.2 to prevent the 7.3 deprecations that affect PHPLoc.

**Comment by adamculp** [comment]
I added a note to the README for future users to know how to handle memory limit errors.
